[tool.poetry]
name = "py-ecom"
version = "0.1.0"
description = ""
authors = ["GalaxUniv <afterhoursbilly@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
flask = "^3.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
